import { Component, input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Project } from '../../../core/models/content.models';
import { RevealDirective } from '../../../shared/directives/reveal.directive';

@Component({ selector: 'app-home-featured-projects', imports: [RouterLink, RevealDirective], template: `<section class="projects section-shell" aria-labelledby="projects-title"><div class="section-heading"><p class="section-label" appReveal>03 / Selected work</p><a class="text-link" routerLink="/projects" appReveal>View all projects <span aria-hidden="true">↗</span></a></div><div class="projects-heading"><h2 id="projects-title" appReveal>Places with<br /><em>purpose.</em></h2><p appReveal>Our work is shaped by context, precision and the people who will use it.</p></div>@if (loading()) { <p class="data-status" role="status">Loading selected work…</p> } @else if (projects().length) { <div class="project-list">@for (project of projects(); track project.id) { <a class="project-card" [routerLink]="['/projects', project.slug]" appReveal><div class="project-media">@if (project.images?.[0]; as image) { <img [src]="image.src" [alt]="image.alt" loading="lazy" /> } @else { <div class="media-placeholder"><span>Project visual</span></div> }</div><div class="project-meta"><div><p class="project-type">{{ project.categories?.[0]?.name ?? 'Featured project' }}</p><h3>{{ project.title }}</h3></div><div class="project-details"><span>{{ project.location ?? 'Location to follow' }}</span><span>{{ project.year ?? '—' }}</span><span aria-hidden="true">↗</span></div></div></a> } </div> } @else { <div class="empty-projects" appReveal><span class="empty-rule"></span><p>Featured projects will appear here as the Howell Group archive is connected.</p><a class="text-link" routerLink="/contact">Discuss a project <span aria-hidden="true">↗</span></a></div> }</section>`, styles: [`
    .projects { padding-bottom: clamp(8rem, 16vw, 16rem); }
    .section-heading { align-items: center; display: flex; justify-content: space-between; } .section-label { color: var(--color-teal); font-size: .68rem; letter-spacing: .15em; margin: 0; text-transform: uppercase; }
    .text-link { border-bottom: 1px solid var(--color-charcoal); color: var(--color-charcoal); font-size: .68rem; letter-spacing: .12em; padding-bottom: .35rem; text-decoration: none; text-transform: uppercase; }
    .projects-heading { align-items: end; display: flex; justify-content: space-between; margin: 4rem 0 5rem; } h2 { font-size: clamp(3.5rem, 8vw, 8rem); letter-spacing: -.075em; line-height: .85; margin: 0; } h2 em { color: var(--color-teal); font-style: normal; } .projects-heading > p { color: var(--color-muted); max-width: 15rem; }
    .project-list { display: grid; gap: clamp(4rem, 9vw, 10rem); } .project-card { color: var(--color-charcoal); display: block; text-decoration: none; } .project-card:nth-child(even) { margin-left: 16%; width: 84%; }
    .project-media { aspect-ratio: 1.9 / 1; background: var(--color-dark-teal); overflow: hidden; } .project-media img { display: block; height: 100%; object-fit: cover; transition: transform .8s cubic-bezier(.2,.7,.2,1); width: 100%; } .project-card:hover img, .project-card:focus-visible img { transform: scale(1.035); } .media-placeholder { align-items: center; background: linear-gradient(125deg, var(--color-dark-teal), var(--color-teal)); color: rgba(255,255,255,.7); display: flex; height: 100%; justify-content: center; letter-spacing: .12em; text-transform: uppercase; }
    .project-meta { align-items: start; border-bottom: 1px solid var(--color-line); display: flex; justify-content: space-between; padding: 1.25rem 0; } .project-type { color: var(--color-teal); font-size: .65rem; letter-spacing: .12em; margin: 0 0 .5rem; text-transform: uppercase; } h3 { font-size: clamp(1.5rem, 3vw, 2.8rem); font-weight: 400; margin: 0; } .project-details { color: var(--color-muted); display: flex; font-size: .7rem; gap: 1.25rem; letter-spacing: .05em; padding-top: 1.6rem; } .project-details span:last-child { color: var(--color-red); font-size: 1.2rem; margin-top: -.35rem; }
    .data-status { border-top: 1px solid var(--color-line); color: var(--color-muted); padding-top: 1.25rem; } .empty-projects { border-top: 1px solid var(--color-line); display: grid; gap: 1.5rem; grid-template-columns: 1fr 1fr; padding-top: 1.25rem; } .empty-projects p { color: var(--color-muted); grid-column: 1; max-width: 24rem; } .empty-projects .text-link { align-self: end; justify-self: end; }
    @media (max-width: 48rem) { .projects-heading { display: block; margin-bottom: 3rem; } .projects-heading > p { margin-top: 2rem; } .project-card:nth-child(even) { margin-left: 0; width: 100%; } .project-media { aspect-ratio: 1.25 / 1; } .project-meta { display: block; } .project-details { padding-top: 1rem; } .empty-projects { display: block; } .empty-projects .text-link { display: inline-block; margin-top: 1rem; } }
  `] })
export class HomeFeaturedProjectsComponent { readonly projects = input<ReadonlyArray<Project>>([]); readonly loading = input(false); }
