import { Component, input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Insight } from '../../../core/models/content.models';
import { RevealDirective } from '../../../shared/directives/reveal.directive';

@Component({ selector: 'app-home-insights', imports: [RouterLink, RevealDirective], template: `<section class="insights section-shell" aria-labelledby="insights-title"><div class="section-heading"><p class="section-label" appReveal>06 / Thinking</p><a class="text-link" routerLink="/insights" appReveal>All insights <span aria-hidden="true">↗</span></a></div><h2 id="insights-title" appReveal>Ideas worth<br /><em>building on.</em></h2>@if (loading()) { <p class="data-status" role="status">Loading insights…</p> } @else if (insights().length) { <div class="insight-grid">@for (insight of insights(); track insight.id) { <a class="insight-card" [routerLink]="['/insights', insight.slug]" appReveal>@if (insight.image; as image) { <img [src]="image.src" [alt]="image.alt" loading="lazy" /> } @else { <div class="insight-placeholder" aria-hidden="true"></div> }<p class="insight-date">{{ insight.date ?? 'Insight' }}</p><h3>{{ insight.title }}</h3><span class="text-link">Read more <span aria-hidden="true">↗</span></span></a> }</div> } @else { <div class="empty-insights" appReveal><p>Insights will appear here as the Howell Group journal is connected.</p><a class="text-link" routerLink="/contact">Stay connected <span aria-hidden="true">↗</span></a></div> }</section>`, styles: [`
    .insights { padding-bottom: clamp(8rem, 16vw, 16rem); } .section-heading { align-items: center; display: flex; justify-content: space-between; } .section-label { color: var(--color-teal); font-size: .68rem; letter-spacing: .15em; margin: 0; text-transform: uppercase; } .text-link { border-bottom: 1px solid var(--color-charcoal); color: var(--color-charcoal); font-size: .68rem; letter-spacing: .12em; padding-bottom: .35rem; text-decoration: none; text-transform: uppercase; } .data-status { border-top: 1px solid var(--color-line); color: var(--color-muted); padding-top: 1.25rem; } h2 { font-size: clamp(3.5rem, 8vw, 8rem); letter-spacing: -.075em; line-height: .85; margin: 5rem 0; } h2 em { color: var(--color-teal); font-style: normal; }
    .insight-grid { display: grid; gap: 2rem; grid-template-columns: repeat(3, 1fr); } .insight-card { color: var(--color-charcoal); text-decoration: none; } .insight-card img, .insight-placeholder { aspect-ratio: 1.15 / 1; background: var(--color-dark-teal); display: block; margin-bottom: 1.2rem; object-fit: cover; width: 100%; } .insight-placeholder { background: linear-gradient(145deg, var(--color-off-white), #d9e1db); border: 1px solid var(--color-line); } .insight-date { color: var(--color-teal); font-size: .63rem; letter-spacing: .12em; text-transform: uppercase; } h3 { font-size: clamp(1.25rem, 2vw, 1.9rem); font-weight: 400; line-height: 1.05; margin: .6rem 0 1.25rem; } .insight-card .text-link { display: inline-block; } .empty-insights { border-top: 1px solid var(--color-line); display: flex; justify-content: space-between; padding-top: 1rem; } .empty-insights p { color: var(--color-muted); }
    @media (max-width: 48rem) { h2 { margin: 3.5rem 0; } .insight-grid { display: block; } .insight-card { display: block; margin-bottom: 3rem; } .empty-insights { display: block; } .empty-insights .text-link { display: inline-block; margin-top: 1rem; } }
  `] })
export class HomeInsightsComponent { readonly insights = input<ReadonlyArray<Insight>>([]); readonly loading = input(false); }
