import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { RevealDirective } from '../../../shared/directives/reveal.directive';

@Component({ selector: 'app-home-about', imports: [RouterLink, RevealDirective], template: `<section class="about section-shell" aria-labelledby="about-title"><div class="about-visual" role="img" aria-label="Abstract architectural elevation"><div class="elevation elevation--back"></div><div class="elevation elevation--front"></div><span class="elevation-mark"></span><p>Context / Detail / Continuity</p></div><div class="about-copy"><p class="section-label" appReveal>05 / The group</p><h2 id="about-title" appReveal>A better way to bring <em>ideas to ground.</em></h2><p class="about-lede" appReveal>We are a group of builders, thinkers and collaborators who believe the best work begins with attention.</p><p class="about-body" appReveal>Our role is to hold the whole picture while respecting every detail. The result is work with a clear point of view, delivered with care.</p><a class="text-link" routerLink="/about" appReveal>About Howell Group <span aria-hidden="true">↗</span></a></div></section>`, styles: [`
    .about { align-items: center; display: grid; gap: 10vw; grid-template-columns: 1fr 1fr; padding-bottom: clamp(8rem, 16vw, 16rem); padding-top: clamp(8rem, 16vw, 16rem); } .section-shell { margin: 0 auto; max-width: var(--content-max-width); padding-left: var(--page-gutter); padding-right: var(--page-gutter); } .section-label { color: var(--color-teal); font-size: .68rem; letter-spacing: .15em; margin: 0; text-transform: uppercase; } .about-copy h2 { font-size: clamp(3rem, 5.5vw, 6rem); letter-spacing: -.07em; line-height: .9; margin: 4rem 0 2.5rem; } h2 em { color: var(--color-teal); font-style: normal; } .about-lede { font-size: clamp(1.1rem, 1.7vw, 1.45rem); line-height: 1.4; max-width: 25rem; } .about-body { color: var(--color-muted); font-size: .9rem; line-height: 1.6; max-width: 22rem; } .text-link { border-bottom: 1px solid var(--color-charcoal); color: var(--color-charcoal); display: inline-block; font-size: .68rem; letter-spacing: .12em; margin-top: 1.5rem; padding-bottom: .35rem; text-decoration: none; text-transform: uppercase; }
    .about-visual { aspect-ratio: .85 / 1; background: var(--color-off-white); border: 1px solid var(--color-line); overflow: hidden; position: relative; } .elevation { border: 1px solid var(--color-teal); height: 70%; left: 14%; position: absolute; top: 15%; transform: skewY(-13deg); width: 70%; } .elevation--back { border-color: var(--color-line); left: 25%; opacity: .8; top: 24%; transform: skewY(13deg); } .elevation--front { background: linear-gradient(90deg, transparent 49%, var(--color-teal) 50%, transparent 51%); background-size: 25% 100%; } .elevation-mark { background: var(--color-red); height: .65rem; left: 14%; position: absolute; top: 15%; width: .65rem; } .about-visual p { bottom: 1rem; color: var(--color-muted); font-size: .63rem; left: 1rem; letter-spacing: .12em; position: absolute; text-transform: uppercase; }
    @media (max-width: 48rem) { .about { display: flex; flex-direction: column; align-items: stretch; } .about-visual { margin: 0 auto; max-width: 28rem; width: 100%; } }
  `] })
export class HomeAboutComponent {}
